sudo: false

language: python

addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -U pip wheel setuptools
  - pip install numpy scipy cython nose
  - python -V

install:
  - pip install .

script:
  - mkdir empty
  - cd empty
  - python -c "import sys;import Gpy;sys.exit(0 if Gpy.test() else 1)"

cache:
  directories:
    - $HOME/.cache/pip