sudo: false

language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -q --use-mirrors numpy scipy Cython
  - python -V

install:
  - pip install .

script:
  - mkdir empty
  - cd empty
  - python -c "import sys;import Gpy;sys.exit(0 if Gpy.test() else 1)"
